### ISSUE TITLE
Freeze on `FMLConstructionEvent`

### ISSUE THREAD

**Issue by Krutoy242** [dragon-forge/HammerLib#54]
On some specific machines, HammerLib makes unable to start minecraft - it causing window freeze / not responding on `FMLConstructionEvent` of `hammerlib` mod:

![image](https://github.com/dragon-forge/HammerLib/assets/936618/c5e31a61-b51e-4f7c-bfd2-524ce6485e43)

The issue was [discovered on E2E-E modpack](https://github.com/Krutoy242/Enigmatica2Expert-Extended/issues/330), but its stably reproducible even with no mods.

There is log of *not responding* when only HammerLib and Thaumcraft installed (we just forgot to remove thaumcraft, it seems like freeze will happen even with only HammerLib): 
### https://mclo.gs/Vz3S7kE

Sometimes, instead of *not responding* window, modpack generate this crash log:
```ruby
java.lang.NoClassDefFoundError: net/minecraftforge/client/model/pipeline/VertexLighterFlat
at net.minecraft.client.renderer.BlockRendererDispatcher.<init>(BlockRendererDispatcher.java:31)
at net.minecraft.client.Minecraft.init(Minecraft.java:525)
[...]
Caused by: java.lang.ClassFormatError: Duplicate field name "rtFullBright" with signature "Z" in class file net/minecraftforge/client/model/pipeline/VertexLighterFlat
at java.lang.ClassLoader.defineClass1(Native Method)
```

### Full log with crash: https://mclo.gs/4lW4Dtf

I know, its not directly pointed to HammerLib, but we found that removing it (and ThaumicAdditions) will fix the issue. There is ["healthy" log](https://mclo.gs/XinwWZt) with HL removed.

I am willing to provide more information and run more tests if needed to solve this problem and allow HammerLib to boot on any computer!

**Comment by Krutoy242** [comment]
Update: It seems like error with `VertexLighterFlat` happens even without HammerLib because even if we remove HammerLib this error still occur https://mclo.gs/EcfJLrU
But stall problem is still actual.

**Comment by ScoutTheSaneless** [comment]
im having similar troubles

**Comment by NuclearGhostUA** [comment]
Error appeared for no obvious reason again. Removing HammerLib (with thaumic additions) solves it btw

**Comment by saQult** [comment]
[this is unreachable in Russia](https://github.com/dragon-forge/HammerLib/blob/1.12.2/src/main/java/com/zeitheron/hammercore/utils/java/io/win32/ModSourceAdapter.java#L148)

basically `HttpRequest.get("https://api.stopmodreposts.org/minecraft/sites.json")` doesnt work in Russia because we have unstable situation with cloudflare (idk about other countries, if you have issues with cloudflare in your country or with your provider this wouldnt work as well)

`stopmodreposts.org` has been blocked in Russia (not this site, but just some issues with cloudflare in Russia)
so I cant load minecraft with hammerlib without any kind of bypass services like zapret or vpn. [*checkhost link*](https://check-host.net/ip-info?host=stopmodreposts.org)

@NuclearGhostUA actually u can run E2E:E normally with zapret or vpn

**Comment by 1tsukusu** [comment]
zapret does not work for this situation anymore, i think
